#!/bin/bash

################################################################################
# NexusBot - Quick Deploy Script
# One-command deployment for NexusBot using Docker
# License: MIT (Free and Open Source)
################################################################################

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
BOT_NAME="NexusBot"
CONTAINER_NAME="nexusbot"
IMAGE_NAME="nexusbot:latest"
CONFIG_DIR="./config"
DATA_DIR="./data"
LOGS_DIR="./logs"
LICENSES_DIR="./licenses"
ENV_FILE=".env"

# Functions
print_banner() {
    echo -e "${BLUE}"
    echo "╔═══════════════════════════════════════════════════════════╗"
    echo "║           ${BOT_NAME} Quick Deploy Script                 ║"
    echo "║         Free & Open Source Telegram Bot                   ║"
    echo "╚═══════════════════════════════════════════════════════════╝"
    echo -e "${NC}"
}

print_step() {
    echo -e "${GREEN}[✓]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[!]${NC} $1"
}

print_error() {
    echo -e "${RED}[✗]${NC} $1"
}

check_requirements() {
    print_step "Checking requirements..."
    
    # Check Docker
    if ! command -v docker &> /dev/null; then
        print_error "Docker is not installed. Please install Docker first."
        echo "Visit: https://docs.docker.com/get-docker/"
        exit 1
    fi
    print_step "Docker found: $(docker --version)"
    
    # Check Docker Compose
    if ! command -v docker-compose &> /dev/null && ! docker compose version &> /dev/null; then
        print_error "Docker Compose is not installed."
        exit 1
    fi
    
    if command -v docker-compose &> /dev/null; then
        COMPOSE_CMD="docker-compose"
    else
        COMPOSE_CMD="docker compose"
    fi
    print_step "Docker Compose found: $($COMPOSE_CMD --version)"
}

create_directories() {
    print_step "Creating necessary directories..."
    
    mkdir -p "$CONFIG_DIR" "$DATA_DIR" "$LOGS_DIR" "$LICENSES_DIR"
    
    # Set permissions
    chmod 755 "$CONFIG_DIR" "$DATA_DIR" "$LOGS_DIR" "$LICENSES_DIR"
    
    print_step "Directories created: config, data, logs, licenses"
}

create_env_file() {
    print_step "Creating environment configuration..."
    
    if [ ! -f "$ENV_FILE" ]; then
        cat > "$ENV_FILE" << EOF
# NexusBot Environment Configuration
# Generated by Quick Deploy Script

# Telegram Bot Token (Get from @BotFather)
BOT_TOKEN=your_bot_token_here

# Admin User IDs (comma-separated Telegram user IDs)
ADMIN_IDS=

# License Settings (false = disabled, true = enabled)
LICENSE_CHECK_ENABLED=false

# Database Configuration
DATABASE_URL=sqlite:///data/nexusbot.db

# Logging Level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
LOG_LEVEL=INFO

# Timezone
TZ=Europe/Moscow

# Optional: Webhook URL (if using webhook instead of polling)
WEBHOOK_URL=

# Optional: Redis URL (if using Redis for caching)
REDIS_URL=
EOF
        print_step "Environment file created: $ENV_FILE"
        print_warning "Please edit $ENV_FILE and set your BOT_TOKEN before starting!"
    else
        print_warning "Environment file already exists: $ENV_FILE"
    fi
}

create_config_files() {
    print_step "Creating default configuration files..."
    
    # Create main config if not exists
    if [ ! -f "$CONFIG_DIR/settings.py" ]; then
        cat > "$CONFIG_DIR/settings.py" << EOF
# NexusBot Configuration
# This file is auto-generated. Edit .env for environment variables.

import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

# Bot Settings
BOT_TOKEN = os.getenv("BOT_TOKEN", "")
ADMIN_IDS = [int(x.strip()) for x in os.getenv("ADMIN_IDS", "").split(",") if x.strip()]

# License Settings
LICENSE_CHECK_ENABLED = os.getenv("LICENSE_CHECK_ENABLED", "false").lower() == "true"

# Database
DATABASE_URL = os.getenv("DATABASE_URL", "sqlite:///data/nexusbot.db")

# Logging
LOG_LEVEL = os.getenv("LOG_LEVEL", "INFO")

# Timezone
TIMEZONE = os.getenv("TZ", "Europe/Moscow")

# Paths
DATA_DIR = BASE_DIR / "data"
LOGS_DIR = BASE_DIR / "logs"
LICENSES_DIR = BASE_DIR / "licenses"
EOF
        print_step "Config file created: $CONFIG_DIR/settings.py"
    fi
}

build_image() {
    print_step "Building Docker image..."
    
    if command -v docker-compose &> /dev/null; then
        COMPOSE_CMD="docker-compose"
    else
        COMPOSE_CMD="docker compose"
    fi
    
    $COMPOSE_CMD build --no-cache
    
    print_step "Docker image built successfully: $IMAGE_NAME"
}

start_container() {
    print_step "Starting NexusBot container..."
    
    if command -v docker-compose &> /dev/null; then
        COMPOSE_CMD="docker-compose"
    else
        COMPOSE_CMD="docker compose"
    fi
    
    $COMPOSE_CMD up -d
    
    print_step "Container started: $CONTAINER_NAME"
}

show_status() {
    echo ""
    print_step "Checking container status..."
    docker ps --filter "name=$CONTAINER_NAME" --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"
    
    echo ""
    print_step "Recent logs:"
    docker logs --tail 10 "$CONTAINER_NAME" 2>/dev/null || print_warning "No logs available yet"
}

show_next_steps() {
    echo ""
    echo "═══════════════════════════════════════════════════════════"
    print_step "Deployment Complete!"
    echo "═══════════════════════════════════════════════════════════"
    echo ""
    echo "Next steps:"
    echo "  1. Edit .env file and set your BOT_TOKEN"
    echo "  2. Restart the container: docker-compose restart"
    echo "  3. Check logs: docker-compose logs -f"
    echo ""
    echo "Useful commands:"
    echo "  • View logs:      docker-compose logs -f"
    echo "  • Stop bot:       docker-compose down"
    echo "  • Restart bot:    docker-compose restart"
    echo "  • Update bot:     ./deploy.sh update"
    echo "  • Backup data:    ./deploy.sh backup"
    echo ""
    echo "Documentation:"
    echo "  • README.md - Full documentation"
    echo "  • DEPLOYMENT.md - Detailed deployment guide"
    echo "  • INSTALL.md - Installation instructions"
    echo ""
    echo "Support: https://github.com/yourusername/nexusbot"
    echo "License: MIT (Free for commercial use)"
    echo "═══════════════════════════════════════════════════════════"
}

backup_data() {
    print_step "Creating backup..."
    
    BACKUP_DIR="./backups/$(date +%Y%m%d_%H%M%S)"
    mkdir -p "$BACKUP_DIR"
    
    cp -r "$DATA_DIR" "$BACKUP_DIR/" 2>/dev/null || true
    cp -r "$CONFIG_DIR" "$BACKUP_DIR/" 2>/dev/null || true
    cp -r "$LICENSES_DIR" "$BACKUP_DIR/" 2>/dev/null || true
    cp "$ENV_FILE" "$BACKUP_DIR/" 2>/dev/null || true
    
    print_step "Backup created: $BACKUP_DIR"
}

update_bot() {
    print_step "Updating NexusBot..."
    
    if command -v docker-compose &> /dev/null; then
        COMPOSE_CMD="docker-compose"
    else
        COMPOSE_CMD="docker compose"
    fi
    
    $COMPOSE_CMD pull
    $COMPOSE_CMD up -d --force-recreate
    
    print_step "Update complete!"
}

# Main script
main() {
    print_banner
    
    case "${1:-deploy}" in
        deploy)
            check_requirements
            create_directories
            create_env_file
            create_config_files
            build_image
            start_container
            show_status
            show_next_steps
            ;;
        start)
            check_requirements
            start_container
            show_status
            ;;
        stop)
            print_step "Stopping NexusBot..."
            docker-compose down
            print_step "Bot stopped"
            ;;
        restart)
            print_step "Restarting NexusBot..."
            docker-compose restart
            show_status
            ;;
        logs)
            docker-compose logs -f
            ;;
        status)
            show_status
            ;;
        update)
            check_requirements
            update_bot
            show_status
            ;;
        backup)
            backup_data
            ;;
        clean)
            print_warning "Removing all containers, images, and volumes..."
            docker-compose down -v --rmi all
            print_step "Cleanup complete"
            ;;
        help|*)
            echo "Usage: $0 {deploy|start|stop|restart|logs|status|update|backup|clean|help}"
            echo ""
            echo "Commands:"
            echo "  deploy   - Full deployment (default)"
            echo "  start    - Start the bot"
            echo "  stop     - Stop the bot"
            echo "  restart  - Restart the bot"
            echo "  logs     - View bot logs"
            echo "  status   - Show bot status"
            echo "  update   - Update to latest version"
            echo "  backup   - Create backup of data"
            echo "  clean    - Remove all containers and data"
            echo "  help     - Show this help message"
            ;;
    esac
}

# Run main function
main "$@"
